//! Encryption for secrets held in the database.
//!
//! The AI provider key has to survive a restart, so it is stored in
//! `ai_settings` — but a provider key in plain text in a database is a key in
//! every backup and every dump. It is therefore sealed with
//! ChaCha20-Poly1305 under a key the server reads from `TM_SECRET_KEY`, and
//! only this module ever sees it in clear.
//!
//! Without `TM_SECRET_KEY` the server keeps the key in memory for the lifetime
//! of the process, exactly as before, rather than writing it out unprotected.

use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use chacha20poly1305::aead::{Aead, OsRng};
use chacha20poly1305::{AeadCore, ChaCha20Poly1305, Key, KeyInit, Nonce};

/// Length of the key `TM_SECRET_KEY` must decode to.
const KEY_LEN: usize = 32;

/// How the sealing key was obtained, which decides how much it protects.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeySource {
    /// `TM_SECRET_KEY`: the key lives outside the database, so a dump of the
    /// database does not reveal the secrets sealed with it.
    Configured,
    /// Generated by the server and stored in the database beside the
    /// ciphertext. Secrets survive a restart and do not appear in plain text
    /// in a row, a log or an API response — but anyone holding the whole
    /// database holds the key too.
    Generated,
}

/// Seals and opens secrets with the configured key.
pub struct SecretStore {
    cipher: ChaCha20Poly1305,
    source: KeySource,
}

impl SecretStore {
    /// Builds a store from raw key bytes, which must be 32 long.
    pub fn from_bytes(key: &[u8], source: KeySource) -> Result<Self, String> {
        if key.len() != KEY_LEN {
            return Err(format!(
                "the key must be {KEY_LEN} bytes, got {}",
                key.len()
            ));
        }
        Ok(Self {
            cipher: ChaCha20Poly1305::new(Key::from_slice(key)),
            source,
        })
    }

    /// A new random key, for the server to store and reuse.
    pub fn generate_key() -> Vec<u8> {
        ChaCha20Poly1305::generate_key(&mut OsRng).to_vec()
    }

    /// Where this store's key came from.
    pub fn source(&self) -> KeySource {
        self.source
    }
    /// Builds a store from `TM_SECRET_KEY`.
    ///
    /// The value is 32 bytes, base64 or hex encoded; generate one with
    /// `openssl rand -base64 32`.
    pub fn from_config(raw: &str) -> Result<Self, String> {
        let key = decode_key(raw)?;
        Self::from_bytes(&key, KeySource::Configured)
    }

    /// Encrypts `plaintext`, returning `(nonce, ciphertext)`.
    ///
    /// A fresh nonce per call: reusing one under the same key would leak the
    /// relationship between two stored secrets.
    pub fn seal(&self, plaintext: &str) -> Result<(Vec<u8>, Vec<u8>), String> {
        let nonce = ChaCha20Poly1305::generate_nonce(&mut OsRng);
        let ciphertext = self
            .cipher
            .encrypt(&nonce, plaintext.as_bytes())
            .map_err(|_| "cannot encrypt the secret".to_owned())?;
        Ok((nonce.to_vec(), ciphertext))
    }

    /// Decrypts a secret sealed by [`SecretStore::seal`].
    ///
    /// Fails if the key changed since it was written, which is the honest
    /// outcome: the stored value cannot be recovered and must be set again.
    pub fn open(&self, nonce: &[u8], ciphertext: &[u8]) -> Result<String, String> {
        if nonce.len() != 12 {
            return Err("stored secret has a malformed nonce".to_owned());
        }
        let plaintext = self
            .cipher
            .decrypt(Nonce::from_slice(nonce), ciphertext)
            .map_err(|_| {
                "cannot decrypt the stored key; TM_SECRET_KEY does not match the one \
                 it was saved with"
                    .to_owned()
            })?;
        String::from_utf8(plaintext).map_err(|_| "stored secret is not valid UTF-8".to_owned())
    }
}

/// Decodes a configured key from base64 or hex.
fn decode_key(raw: &str) -> Result<Vec<u8>, String> {
    let raw = raw.trim();
    let bytes = if raw.len() == KEY_LEN * 2 && raw.chars().all(|c| c.is_ascii_hexdigit()) {
        (0..raw.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&raw[i..i + 2], 16))
            .collect::<Result<Vec<_>, _>>()
            .map_err(|_| "TM_SECRET_KEY is not valid hex".to_owned())?
    } else {
        BASE64
            .decode(raw)
            .map_err(|_| "TM_SECRET_KEY is neither base64 nor hex".to_owned())?
    };
    if bytes.len() != KEY_LEN {
        return Err(format!(
            "TM_SECRET_KEY must decode to {KEY_LEN} bytes, got {}",
            bytes.len()
        ));
    }
    Ok(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    const KEY: &str = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=";

    #[test]
    fn round_trips_a_secret() {
        let store = SecretStore::from_config(KEY).unwrap();
        let (nonce, ciphertext) = store.seal("sk-ant-secret").unwrap();
        assert_eq!(store.open(&nonce, &ciphertext).unwrap(), "sk-ant-secret");
    }

    #[test]
    fn ciphertext_does_not_contain_the_secret() {
        let store = SecretStore::from_config(KEY).unwrap();
        let (_, ciphertext) = store.seal("sk-ant-secret").unwrap();
        assert!(!String::from_utf8_lossy(&ciphertext).contains("sk-ant"));
    }

    #[test]
    fn uses_a_fresh_nonce_each_time() {
        // Reusing a nonce under one key is the classic way to break this.
        let store = SecretStore::from_config(KEY).unwrap();
        let (a, _) = store.seal("same").unwrap();
        let (b, _) = store.seal("same").unwrap();
        assert_ne!(a, b);
    }

    #[test]
    fn another_key_cannot_open_it() {
        let store = SecretStore::from_config(KEY).unwrap();
        let (nonce, ciphertext) = store.seal("sk-ant-secret").unwrap();
        let other =
            SecretStore::from_config("ZmVkY2JhOTg3NjU0MzIxMGZlZGNiYTk4NzY1NDMyMTA=").unwrap();
        assert!(other.open(&nonce, &ciphertext).is_err());
    }

    #[test]
    fn rejects_a_tampered_ciphertext() {
        let store = SecretStore::from_config(KEY).unwrap();
        let (nonce, mut ciphertext) = store.seal("sk-ant-secret").unwrap();
        ciphertext[0] ^= 0xff;
        assert!(store.open(&nonce, &ciphertext).is_err());
    }

    #[test]
    fn accepts_hex_as_well_as_base64() {
        let hex =
            "30313233343536373839616263646566303132333435363738396162636465 66".replace(' ', "");
        assert!(SecretStore::from_config(&hex).is_ok());
    }

    #[test]
    fn a_generated_key_round_trips_and_is_marked_as_such() {
        let key = SecretStore::generate_key();
        let store = SecretStore::from_bytes(&key, KeySource::Generated).unwrap();
        let (nonce, ciphertext) = store.seal("sk-ollama").unwrap();
        assert_eq!(store.open(&nonce, &ciphertext).unwrap(), "sk-ollama");
        assert_eq!(store.source(), KeySource::Generated);
    }

    #[test]
    fn generated_keys_differ() {
        assert_ne!(SecretStore::generate_key(), SecretStore::generate_key());
    }

    #[test]
    fn rejects_raw_key_bytes_of_the_wrong_length() {
        assert!(SecretStore::from_bytes(&[0u8; 8], KeySource::Generated).is_err());
    }

    #[test]
    fn rejects_a_key_of_the_wrong_length() {
        assert!(SecretStore::from_config("c2hvcnQ=").is_err());
        assert!(SecretStore::from_config("not base64 at all !!").is_err());
    }
}
